# Generated by Django 3.2.25 on 2025-06-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField(blank=True)),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
