# Generated by Django 3.2.25 on 2025-06-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='name',
            new_name='title',
        ),
    ]
