# Generated by Django 3.2.25 on 2025-06-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exsentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exsentence',
            old_name='name',
            new_name='sentence',
        ),
    ]
