# Generated by Django 3.2.25 on 2025-06-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_name_exsentence_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exsentence',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exSentences', to='core.word'),
        ),
    ]
