# Generated by Django 3.2.25 on 2025-06-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userword_unique_user_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
